import { useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { api } from '../../lib/api';
import { readCache, saveCache } from '../../lib/cache';
import { useI18n } from '../../lib/i18n';
export default function Advisory() {
  const { t } = useI18n(); const [data, setData] = useState<any>(readCache<any>('advice')); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  async function generate() { setLoading(true); setError(''); try { const result = await api.recommendations(); setData(result); saveCache('advice', result); } catch (e: any) { setError(e.message || t.unavailable); } finally { setLoading(false); } }
  return <ScrollView contentContainerStyle={s.page}><View style={s.top}><Text style={s.kicker}>AG-02 · CROP RECOMMENDATION</Text><Text style={s.title}>What should you grow next?</Text><Text style={s.text}>Each score is computed by the live advisory engine from season, soil, moisture, rainfall, rotation, and disease history.</Text>{data && <Text style={s.source}>{t.source}: {data.weatherSummary.source}</Text>}<Pressable style={s.button} onPress={generate}><Text style={s.buttonText}>{loading ? 'Analysing conditions…' : t.generate}</Text></Pressable>{loading && <ActivityIndicator color="#176b3a" />}</View>
    {error && <View style={s.alert}><Text style={s.alertTitle}>{t.unavailable}</Text><Text style={s.text}>{error}</Text></View>}{!data && !loading && <Text style={s.text}>Generate an advisory to retrieve live weather and computed crop rankings.</Text>}
    {data && <><Text style={s.section}>{t.recommendations}</Text>{data.recommendations.map((item: any, index: number) => <View style={s.card} key={item.crop}><View style={s.row}><View style={s.rank}><Text style={s.rankText}>{index + 1}</Text></View><View style={s.crop}><Text style={s.cropName}>{item.crop}</Text><Text style={s.match}>{item.confidence}% match</Text></View></View><View style={s.line} />{item.why.map((reason: string) => <Text key={reason} style={s.reason}>✓ {reason}</Text>)}</View>)}
    <Text style={s.section}>{t.alerts}</Text>{data.alerts.map((alert: any) => <View style={s.alert} key={alert.message}><Text style={s.alertTitle}>⚠ {alert.severity?.toUpperCase() || 'NOTICE'}</Text><Text style={s.text}>{alert.message}</Text></View>)}</>}
  </ScrollView>;
}
const s = StyleSheet.create({ page: { padding: 16, backgroundColor: '#f5f8f1', gap: 13, paddingBottom: 32 }, top: { backgroundColor: '#dff0db', borderRadius: 18, padding: 17, gap: 8 }, kicker: { color: '#48704d', fontWeight: '900', fontSize: 10, letterSpacing: 1 }, title: { color: '#16452b', fontSize: 24, fontWeight: '800' }, text: { color: '#49604e', lineHeight: 19, fontSize: 13 }, source: { color: '#176b3a', fontWeight: '700', fontSize: 12 }, button: { backgroundColor: '#176b3a', borderRadius: 10, padding: 13, alignItems: 'center', marginTop: 4 }, buttonText: { color: '#fff', fontWeight: '800' }, section: { color: '#173e27', fontSize: 18, fontWeight: '800', marginTop: 4 }, card: { backgroundColor: '#fff', padding: 15, borderRadius: 15, gap: 7, elevation: 1 }, row: { flexDirection: 'row', alignItems: 'center', gap: 10 }, rank: { height: 31, width: 31, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: '#e1f1dc' }, rankText: { color: '#176b3a', fontWeight: '900' }, crop: { flex: 1, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, cropName: { color: '#16452b', fontSize: 18, fontWeight: '800' }, match: { color: '#176b3a', backgroundColor: '#e1f1dc', padding: 5, borderRadius: 7, fontSize: 11, fontWeight: '800' }, line: { height: 1, backgroundColor: '#e5ede3' }, reason: { color: '#526557', fontSize: 13, lineHeight: 19 }, alert: { backgroundColor: '#fff1d1', borderRadius: 12, padding: 14, gap: 4 }, alertTitle: { color: '#956000', fontWeight: '900', fontSize: 11 } });
