import { useState } from 'react';
import { ActivityIndicator, Alert, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { api } from '../../lib/api';
import { useI18n } from '../../lib/i18n';
export default function Diagnose() {
  const { t } = useI18n(); const [uri, setUri] = useState<string>(); const [result, setResult] = useState<any>(); const [loading, setLoading] = useState(false);
  async function pick(useCamera: boolean) { const permission = useCamera ? await ImagePicker.requestCameraPermissionsAsync() : await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) return Alert.alert('Permission needed', 'Allow access to add a leaf image.'); const image = useCamera ? await ImagePicker.launchCameraAsync({ mediaTypes: ['images'], quality: 0.7 }) : await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], quality: 0.7 }); if (image.canceled) return; const nextUri = image.assets[0].uri; setUri(nextUri); setResult(undefined); setLoading(true); try { setResult(await api.detect(nextUri)); } catch (error: any) { Alert.alert('Analysis unavailable', `${error.message}. Make sure the Express and FastAPI services are running.`); } finally { setLoading(false); } }
  return <ScrollView contentContainerStyle={s.page}><View style={s.hero}><Text style={s.kicker}>AG-01 · DISEASE DETECTION</Text><Text style={s.title}>{t.diseaseTitle}</Text><Text style={s.text}>Use one well-lit leaf against a plain background. Results are stored with your farmer record.</Text></View>
    <View style={s.photoBox}>{uri ? <Image source={{ uri }} style={s.photo} /> : <><Text style={s.leaf}>⌁</Text><Text style={s.placeholder}>{t.noPhoto}</Text></>}</View><View style={s.buttons}><Pressable style={s.primary} onPress={() => pick(true)}><Text style={s.primaryText}>{t.openCamera}</Text></Pressable><Pressable style={s.secondary} onPress={() => pick(false)}><Text style={s.secondaryText}>{t.chooseImage}</Text></Pressable></View>{loading && <ActivityIndicator size="large" color="#176b3a" />}
    {result && <View style={[s.result, result.clearDetection ? s.positive : s.neutral]}><Text style={s.resultKicker}>{result.clearDetection ? t.analysis.toUpperCase() : 'IMAGE NEEDS REVIEW'}</Text><Text style={s.disease}>{result.disease}</Text><Text style={s.confidence}>Confidence: {result.confidence}%</Text>{result.guidance.map((tip: string) => <Text key={tip} style={s.tip}>• {tip}</Text>)}</View>}
    <View style={s.note}><Text style={s.noteTitle}>Responsible use</Text><Text style={s.text}>This is a decision-support tool. Confirm severe or spreading disease with a local agriculture officer before applying treatment.</Text></View>
  </ScrollView>;
}
const s = StyleSheet.create({ page: { padding: 16, backgroundColor: '#f5f8f1', gap: 13, paddingBottom: 32 }, hero: { backgroundColor: '#e0f0dc', padding: 17, borderRadius: 18, gap: 7 }, kicker: { color: '#4b714f', fontSize: 10, fontWeight: '900', letterSpacing: 1 }, title: { color: '#16452b', fontSize: 25, fontWeight: '800' }, text: { color: '#4d6250', lineHeight: 19, fontSize: 13 }, photoBox: { height: 250, backgroundColor: '#e9eee5', borderRadius: 17, justifyContent: 'center', alignItems: 'center', overflow: 'hidden' }, leaf: { color: '#7ca17a', fontSize: 58 }, placeholder: { color: '#6a7d6c', fontWeight: '700' }, photo: { width: '100%', height: '100%', resizeMode: 'cover' }, buttons: { gap: 9 }, primary: { backgroundColor: '#176b3a', borderRadius: 10, alignItems: 'center', padding: 13 }, primaryText: { color: '#fff', fontWeight: '800' }, secondary: { borderColor: '#176b3a', borderWidth: 1, borderRadius: 10, alignItems: 'center', padding: 12 }, secondaryText: { color: '#176b3a', fontWeight: '800' }, result: { borderRadius: 15, padding: 15, gap: 6 }, positive: { backgroundColor: '#e0f0dc' }, neutral: { backgroundColor: '#fff1d1' }, resultKicker: { fontSize: 10, color: '#4a704e', fontWeight: '900', letterSpacing: 1 }, disease: { fontSize: 21, color: '#16452b', fontWeight: '800' }, confidence: { color: '#38583f', fontWeight: '700' }, tip: { color: '#4b604e', fontSize: 13, lineHeight: 20 }, note: { backgroundColor: '#fff', padding: 15, borderRadius: 13, gap: 5 }, noteTitle: { color: '#16452b', fontWeight: '800' } });
