import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { api } from '../../lib/api';
import { defaultProfile } from '../../lib/demo';
import { readCache, saveCache } from '../../lib/cache';
import { useI18n } from '../../lib/i18n';
export default function Dashboard() {
  const { t } = useI18n(); const [profile, setProfile] = useState(defaultProfile); const [advice, setAdvice] = useState<any>(); const [live, setLive] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  useEffect(() => { api.profile().then((p) => { setProfile(p); saveCache('profile', p); setLive(true); }).catch(() => { const saved = readCache<typeof defaultProfile>('profile'); if (saved) setProfile(saved); }); }, []);
  async function refresh() { setLoading(true); setError(''); try { const data = await api.recommendations(); setAdvice(data); saveCache('advice', data); setLive(true); } catch (e: any) { setError(e.message || t.unavailable); } finally { setLoading(false); } }
  const active = advice || readCache<any>('advice');
  return <ScrollView contentContainerStyle={s.page}><View style={s.hero}><Text style={s.kicker}>SMART CROP ADVISORY</Text><Text style={s.title}>{t.greeting}, {profile.name} 🌾</Text><Text style={s.heroText}>Personalized field decisions for {profile.region}.</Text><View style={s.badge}><Text style={s.badgeText}>{live ? `● ${t.live.toUpperCase()}` : `● ${t.unavailable.toUpperCase()}`}</Text></View></View>
    <View style={s.stats}><Stat label="SOIL" value={profile.soilType} icon="◒" /><Stat label="MOISTURE" value={profile.soilMoisture} icon="◈" /><Stat label="LAND" value={`${profile.landSizeAcres} ac`} icon="⌁" /></View>
    <Text style={s.section}>{t.fieldBrief}</Text><View style={s.brief}>{active ? <><Text style={s.briefTitle}>Rain outlook · {active.weatherSummary.rainNext7DaysMm} mm this week</Text><Text style={s.body}>Source: {active.weatherSummary.source}</Text></> : <Text style={s.body}>{error || 'Refresh to retrieve the current forecast and recommendations.'}</Text>}<Pressable style={s.primary} onPress={refresh}><Text style={s.primaryText}>{loading ? 'Refreshing…' : t.refresh}</Text></Pressable>{loading && <ActivityIndicator color="#fff" />}</View>
    {active && <><Text style={s.section}>{t.alerts}</Text>{active.alerts.slice(0, 2).map((a: any) => <View style={s.alert} key={a.message}><Text style={s.alertLabel}>FIELD ALERT</Text><Text style={s.body}>⚠ {a.message}</Text></View>)}</>}
    <View style={s.grid}><Action icon="☁" label={t.cropAdvice} onPress={() => router.push('/advisory')} /><Action icon="⌁" label={t.scanLeaf} onPress={() => router.push('/diagnose')} /></View>
  </ScrollView>;
}
function Stat({ label, value, icon }: any) { return <View style={s.stat}><Text style={s.icon}>{icon}</Text><Text style={s.statLabel}>{label}</Text><Text style={s.statValue}>{value}</Text></View>; }
function Action({ icon, label, onPress }: any) { return <Pressable style={s.action} onPress={onPress}><Text style={s.actionIcon}>{icon}</Text><Text style={s.actionText}>{label}</Text><Text style={s.arrow}>→</Text></Pressable>; }
const s = StyleSheet.create({ page: { padding: 16, gap: 14, backgroundColor: '#f5f8f1', paddingBottom: 32 }, hero: { backgroundColor: '#176b3a', padding: 21, borderRadius: 22, gap: 7 }, kicker: { color: '#bfe4ba', fontSize: 11, fontWeight: '800', letterSpacing: 1.2 }, title: { color: '#fff', fontSize: 27, fontWeight: '800' }, heroText: { color: '#d9efd7', fontSize: 14 }, badge: { alignSelf: 'flex-start', backgroundColor: '#235c35', paddingHorizontal: 9, paddingVertical: 6, borderRadius: 8, marginTop: 6 }, badgeText: { color: '#c6ebc1', fontSize: 10, fontWeight: '800' }, stats: { flexDirection: 'row', gap: 8 }, stat: { flex: 1, backgroundColor: '#fff', borderRadius: 13, padding: 11, elevation: 1 }, icon: { color: '#176b3a', fontWeight: '800' }, statLabel: { color: '#738175', fontSize: 9, fontWeight: '800', marginTop: 5 }, statValue: { color: '#1b4028', fontWeight: '800', fontSize: 13, textTransform: 'capitalize' }, section: { color: '#183e27', fontWeight: '800', fontSize: 18, marginTop: 3 }, brief: { backgroundColor: '#e0f0dc', borderRadius: 16, padding: 16, gap: 8 }, briefTitle: { color: '#16452b', fontSize: 16, fontWeight: '800' }, body: { color: '#445a49', lineHeight: 19, fontSize: 13 }, primary: { backgroundColor: '#176b3a', borderRadius: 10, padding: 13, alignItems: 'center', marginTop: 3 }, primaryText: { color: '#fff', fontWeight: '800' }, alert: { backgroundColor: '#fff0cf', borderRadius: 12, padding: 13, gap: 4 }, alertLabel: { color: '#9d6900', fontSize: 10, fontWeight: '900', letterSpacing: 1 }, grid: { flexDirection: 'row', gap: 10 }, action: { flex: 1, backgroundColor: '#fff', padding: 15, borderRadius: 14, elevation: 1 }, actionIcon: { color: '#176b3a', fontSize: 20 }, actionText: { color: '#193e27', fontWeight: '800', marginTop: 10 }, arrow: { color: '#176b3a', fontSize: 20, marginTop: 6 } });
