import { useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { api } from '../../lib/api';
import { defaultProfile } from '../../lib/demo';
import { readCache, saveCache } from '../../lib/cache';
import { languages, useI18n } from '../../lib/i18n';
export default function Profile() {
  const { language, setLanguage, t } = useI18n(); const [profile, setProfile] = useState<any>(defaultProfile); const [live, setLive] = useState(false);
  useEffect(() => { api.profile().then((data) => { setProfile(data); setLive(true); saveCache('profile', data); }).catch(() => { const saved = readCache<any>('profile'); if (saved) setProfile(saved); }); }, []);
  function change(key: string, value: string) { setProfile((old: any) => ({ ...old, [key]: ['landSizeAcres', 'latitude', 'longitude'].includes(key) ? Number(value) || 0 : value })); }
  async function save() { const next = { ...profile, language }; saveCache('profile', next); try { await api.saveProfile(next); setLive(true); Alert.alert('Profile saved', 'Your next advisory will use these farm details.'); } catch { Alert.alert('Saved on this device', 'Start the API to sync this profile to Firebase.'); } }
  return <ScrollView contentContainerStyle={s.page}><View style={s.hero}><Text style={s.avatar}>{profile.name?.slice(0, 1).toUpperCase() || 'F'}</Text><View><Text style={s.title}>{profile.name || t.profile}</Text><Text style={s.subtitle}>{profile.region}</Text><Text style={s.status}>{live ? `● ${t.live}` : `● ${t.unavailable}`}</Text></View></View>
    <View style={s.card}><Text style={s.kicker}>{t.onboarding.toUpperCase()}</Text><Text style={s.cardTitle}>Tell us about your field</Text><Field label={t.name} value={profile.name} onChangeText={(v: string) => change('name', v)} /><Field label={t.region} value={profile.region} onChangeText={(v: string) => change('region', v)} /><Field label="Latitude" value={String(profile.latitude ?? '')} keyboardType="decimal-pad" onChangeText={(v: string) => change('latitude', v)} /><Field label="Longitude" value={String(profile.longitude ?? '')} keyboardType="decimal-pad" onChangeText={(v: string) => change('longitude', v)} /><Field label={`${t.soil} (loamy, clayey, sandy loam)`} value={profile.soilType} onChangeText={(v: string) => change('soilType', v)} /><Field label={`${t.moisture} (low, moderate, adequate)`} value={profile.soilMoisture} onChangeText={(v: string) => change('soilMoisture', v)} /><Field label={t.land} value={String(profile.landSizeAcres)} keyboardType="numeric" onChangeText={(v: string) => change('landSizeAcres', v)} /><Text style={s.label}>{t.language}</Text><View style={s.languageGrid}>{languages.map((item) => <Pressable key={item.code} onPress={() => setLanguage(item.code)} style={[s.language, language === item.code && s.languageActive]}><Text style={[s.languageText, language === item.code && s.languageTextActive]}>{item.label}</Text></Pressable>)}</View><Pressable style={s.save} onPress={save}><Text style={s.saveText}>{t.save}</Text></Pressable></View>
    <View style={s.info}><Text style={s.infoTitle}>How this improves advice</Text><Text style={s.infoText}>Soil, moisture, region, and crop history influence the ranking and explanation for every crop recommendation.</Text></View>
  </ScrollView>;
}
function Field({ label, ...inputProps }: any) { return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput style={s.input} {...inputProps} /></View>; }
const s = StyleSheet.create({ page: { padding: 16, backgroundColor: '#f5f8f1', gap: 14, paddingBottom: 32 }, hero: { backgroundColor: '#176b3a', borderRadius: 18, padding: 17, flexDirection: 'row', alignItems: 'center', gap: 13 }, avatar: { color: '#176b3a', backgroundColor: '#d8efcf', height: 52, width: 52, textAlign: 'center', textAlignVertical: 'center', borderRadius: 26, fontWeight: '900', fontSize: 23 }, title: { color: '#fff', fontSize: 21, fontWeight: '800' }, subtitle: { color: '#d7ecd4', marginTop: 2 }, status: { color: '#c0eabb', marginTop: 6, fontSize: 11, fontWeight: '700' }, card: { backgroundColor: '#fff', padding: 16, borderRadius: 16, gap: 9, elevation: 1 }, kicker: { color: '#547a58', fontSize: 10, fontWeight: '900', letterSpacing: 1 }, cardTitle: { color: '#16452b', fontSize: 19, fontWeight: '800', marginBottom: 3 }, field: { gap: 4 }, label: { color: '#526557', fontSize: 12, fontWeight: '700' }, input: { borderWidth: 1, borderColor: '#d7e3d4', backgroundColor: '#fbfdf9', padding: 10, borderRadius: 9, color: '#173a23' }, languageGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, language: { borderWidth: 1, borderColor: '#cadbc9', borderRadius: 8, paddingHorizontal: 9, paddingVertical: 7 }, languageActive: { backgroundColor: '#176b3a', borderColor: '#176b3a' }, languageText: { color: '#31523a', fontSize: 12, fontWeight: '700' }, languageTextActive: { color: '#fff' }, save: { backgroundColor: '#176b3a', borderRadius: 10, padding: 13, alignItems: 'center', marginTop: 4 }, saveText: { color: '#fff', fontWeight: '800' }, info: { backgroundColor: '#e0f0dc', padding: 14, borderRadius: 13, gap: 4 }, infoTitle: { color: '#16452b', fontWeight: '800' }, infoText: { color: '#4b604e', fontSize: 13, lineHeight: 19 } });
