import { createContext, useContext, useEffect, useMemo, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type Language = 'en' | 'hi' | 'pa' | 'bn' | 'mr' | 'ta' | 'te' | 'gu';
export const languages: { code: Language; label: string }[] = [{ code: 'en', label: 'English' }, { code: 'hi', label: 'हिन्दी' }, { code: 'pa', label: 'ਪੰਜਾਬੀ' }, { code: 'bn', label: 'বাংলা' }, { code: 'mr', label: 'मराठी' }, { code: 'ta', label: 'தமிழ்' }, { code: 'te', label: 'తెలుగు' }, { code: 'gu', label: 'ગુજરાતી' }];
const en = { home: 'Home', advisory: 'Advisory', diagnose: 'Diagnose', profile: 'Profile', greeting: 'Namaste', live: 'Live services connected', refresh: 'Refresh personalized advice', cropAdvice: 'Crop advisory', scanLeaf: 'Scan leaf', fieldBrief: 'Today’s field brief', recommendations: 'Ranked crop choices', alerts: 'Action alerts', generate: 'Generate fresh advisory', openCamera: 'Open camera', chooseImage: 'Choose image', diseaseTitle: 'Inspect a leaf early.', noPhoto: 'No leaf photo selected', save: 'Save farm profile', onboarding: 'Farmer onboarding', name: 'Farmer name', region: 'Village / block / district', soil: 'Soil type', moisture: 'Soil moisture', land: 'Land size in acres', language: 'Preferred language', source: 'Weather source', analysis: 'Analysis complete', unavailable: 'Service unavailable', retry: 'Try again' };
const packs: Record<Language, Partial<typeof en>> = {
  en, hi: { home: 'होम', advisory: 'सलाह', diagnose: 'रोग जांच', profile: 'प्रोफ़ाइल', greeting: 'नमस्ते', live: 'लाइव सेवाएं जुड़ी हैं', refresh: 'व्यक्तिगत सलाह रिफ्रेश करें', cropAdvice: 'फसल सलाह', scanLeaf: 'पत्ता स्कैन करें', fieldBrief: 'आज की खेत जानकारी', recommendations: 'क्रमबद्ध फसल विकल्प', alerts: 'कार्रवाई अलर्ट', generate: 'नई सलाह बनाएं', openCamera: 'कैमरा खोलें', chooseImage: 'चित्र चुनें', diseaseTitle: 'पत्ते की जल्दी जांच करें।', noPhoto: 'कोई पत्ता फोटो नहीं चुना', save: 'खेत प्रोफ़ाइल सहेजें', onboarding: 'किसान पंजीकरण', language: 'पसंदीदा भाषा', source: 'मौसम स्रोत', analysis: 'विश्लेषण पूरा हुआ', unavailable: 'सेवा उपलब्ध नहीं है', retry: 'फिर प्रयास करें' },
  pa: { home: 'ਹੋਮ', advisory: 'ਸਲਾਹ', diagnose: 'ਰੋਗ ਜਾਂਚ', profile: 'ਪ੍ਰੋਫਾਈਲ', greeting: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ', live: 'ਲਾਈਵ ਸੇਵਾਵਾਂ ਜੁੜੀਆਂ ਹਨ', refresh: 'ਨਿੱਜੀ ਸਲਾਹ ਤਾਜ਼ਾ ਕਰੋ', cropAdvice: 'ਫਸਲ ਸਲਾਹ', scanLeaf: 'ਪੱਤਾ ਸਕੈਨ ਕਰੋ', fieldBrief: 'ਅੱਜ ਦੀ ਖੇਤ ਜਾਣਕਾਰੀ', recommendations: 'ਫਸਲ ਵਿਕਲਪਾਂ ਦੀ ਰੈਂਕਿੰਗ', alerts: 'ਕਾਰਵਾਈ ਚੇਤਾਵਨੀਆਂ', generate: 'ਨਵੀਂ ਸਲਾਹ ਬਣਾਓ', openCamera: 'ਕੈਮਰਾ ਖੋਲ੍ਹੋ', chooseImage: 'ਤਸਵੀਰ ਚੁਣੋ', diseaseTitle: 'ਪੱਤੇ ਦੀ ਜਲਦੀ ਜਾਂਚ ਕਰੋ।', noPhoto: 'ਕੋਈ ਪੱਤੇ ਦੀ ਤਸਵੀਰ ਨਹੀਂ', save: 'ਖੇਤ ਪ੍ਰੋਫਾਈਲ ਸੇਵ ਕਰੋ', onboarding: 'ਕਿਸਾਨ ਰਜਿਸਟ੍ਰੇਸ਼ਨ', language: 'ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ', source: 'ਮੌਸਮ ਸਰੋਤ', analysis: 'ਵਿਸ਼ਲੇਸ਼ਣ ਪੂਰਾ ਹੋਇਆ', unavailable: 'ਸੇਵਾ ਉਪਲਬਧ ਨਹੀਂ', retry: 'ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ' },
  bn: { home: 'হোম', advisory: 'পরামর্শ', diagnose: 'রোগ নির্ণয়', profile: 'প্রোফাইল', greeting: 'নমস্কার', refresh: 'পরামর্শ রিফ্রেশ করুন', cropAdvice: 'ফসল পরামর্শ', scanLeaf: 'পাতা স্ক্যান করুন', alerts: 'সতর্কতা', openCamera: 'ক্যামেরা খুলুন', chooseImage: 'ছবি বাছুন', save: 'খামার প্রোফাইল সংরক্ষণ করুন', language: 'পছন্দের ভাষা', unavailable: 'পরিষেবা উপলব্ধ নয়' },
  mr: { home: 'मुख्यपृष्ठ', advisory: 'सल्ला', diagnose: 'रोग तपासणी', profile: 'प्रोफाइल', greeting: 'नमस्कार', refresh: 'वैयक्तिक सल्ला अद्ययावत करा', cropAdvice: 'पीक सल्ला', scanLeaf: 'पान स्कॅन करा', alerts: 'सूचना', openCamera: 'कॅमेरा उघडा', chooseImage: 'प्रतिमा निवडा', save: 'शेत प्रोफाइल जतन करा', language: 'पसंतीची भाषा', unavailable: 'सेवा उपलब्ध नाही' },
  ta: { home: 'முகப்பு', advisory: 'ஆலோசனை', diagnose: 'நோய் கண்டறிதல்', profile: 'சுயவிவரம்', greeting: 'வணக்கம்', refresh: 'ஆலோசனையை புதுப்பிக்கவும்', cropAdvice: 'பயிர் ஆலோசனை', scanLeaf: 'இலையை ஸ்கேன் செய்க', alerts: 'எச்சரிக்கைகள்', openCamera: 'கேமராவை திறக்கவும்', chooseImage: 'படத்தை தேர்ந்தெடுக்கவும்', save: 'பண்ணை சுயவிவரத்தை சேமிக்கவும்', language: 'விருப்ப மொழி', unavailable: 'சேவை கிடைக்கவில்லை' },
  te: { home: 'హోమ్', advisory: 'సలహా', diagnose: 'వ్యాధి నిర్ధారణ', profile: 'ప్రొఫైల్', greeting: 'నమస్కారం', refresh: 'సలహాను రిఫ్రెష్ చేయండి', cropAdvice: 'పంట సలహా', scanLeaf: 'ఆకును స్కాన్ చేయండి', alerts: 'హెచ్చరికలు', openCamera: 'కెమెరా తెరవండి', chooseImage: 'చిత్రాన్ని ఎంచుకోండి', save: 'వ్యవసాయ ప్రొఫైల్ సేవ్ చేయండి', language: 'ఇష్టమైన భాష', unavailable: 'సేవ అందుబాటులో లేదు' },
  gu: { home: 'હોમ', advisory: 'સલાહ', diagnose: 'રોગ તપાસ', profile: 'પ્રોફાઇલ', greeting: 'નમસ્તે', refresh: 'સલાહ તાજી કરો', cropAdvice: 'પાક સલાહ', scanLeaf: 'પાંદડું સ્કેન કરો', alerts: 'ચેતવણીઓ', openCamera: 'કૅમેરા ખોલો', chooseImage: 'છબી પસંદ કરો', save: 'ખેતર પ્રોફાઇલ સાચવો', language: 'પસંદીદા ભાષા', unavailable: 'સેવા ઉપલબ્ધ નથી' }
};
const I18n = createContext({ language: 'en' as Language, setLanguage: async (_: Language) => {}, t: en });
export function I18nProvider({ children }: { children: React.ReactNode }) { const [language, set] = useState<Language>('en'); useEffect(() => { AsyncStorage.getItem('language').then((value) => { if (value && value in packs) set(value as Language); }); }, []); const setLanguage = async (value: Language) => { set(value); await AsyncStorage.setItem('language', value); }; const t = useMemo(() => ({ ...en, ...packs[language] }), [language]); return <I18n.Provider value={{ language, setLanguage, t }}>{children}</I18n.Provider>; }
export const useI18n = () => useContext(I18n);
